<a href="https://colab.research.google.com/github/Omjd12/Omjadhav/blob/main/DL_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

def sigmoid(z):
  return 1/(1+np.exp(-z))

def relu(z):
  return np.maximum(0, z)

def tanh(z):
  return np.tanh(z)

def neurons(x, w, b, Activation = None):
  z = np.dot(x, w) + b
  if Activation is None:
    return z
  return Activation(z)

x = np.random.randint(0, 3,size = (3,1))
w = np.random.randint(0, 3, size = (1,3))
result = neurons(x,w, 4)
print(result)
result = neurons(x , w, 1, Activation= tanh)
print(result)
result = neurons(x, w, 2, Activation= relu)
print(result)
result = neurons(x, w, 1, Activation= sigmoid)
print(result)



[[6 5 4]
 [8 6 4]
 [4 4 4]]
[[0.99505475 0.96402758 0.76159416]
 [0.9999092  0.99505475 0.76159416]
 [0.76159416 0.76159416 0.76159416]]
[[4 3 2]
 [6 4 2]
 [2 2 2]]
[[0.95257413 0.88079708 0.73105858]
 [0.99330715 0.95257413 0.73105858]
 [0.73105858 0.73105858 0.73105858]]
